//to display the sum of 2 arrays
#include <iostream>
using namespace std;
int main() {
int n;
cout<<"enter the size of both the arrays";
cin>>n;
int A[n],B[n],C[n];
cout<<"enter the elements of 1st array";
for(int i=0;i<n;i++)
{
cin>>A[i];
}
cout<<"enter the elements of 2nd array";
for(int i=0;i<n;i++)
{
cin>>B[i];
}
for(int i=0;i<n;i++)
{
    C[i]=A[i]+B[i];
    cout<<C[i]<<" ";
}
    return 0;
}
